v0.15.0 update: Config watcher, refactoring, fixes and doc update
l7mp/stunner-helm pull request #12
Opened 2023-04-14 12:03 UTC by davidkornel

Needs some work:

- [ ] README Section about dev releases
- [ ] README Include a table of fields explaining them (not so sure if it's necessary)
- [ ] Operator-gateway: Auth service include 

Documentation update:
- Readme now includes some of the most important features. How to use and what to know about them.

Fix and refactor(/helm):
-Changed pullPolicy in both stunner and operator helm to IfNotPresent.
(During stable release there is no point in pulling over and over again)
-Refactored stunner/values.yaml to make it more suitable for the following point.
-StartupProbe added to stunner to prevent `kubelet` from terminating the pod even before picking up the `stunnerd.conf` 

New feature: Config watcher
- Introduced config watcher as an option (default). This means an extra sidecar is added next to stunnerd.
Added a new template file for the RBAC resources.

2023-04-19 14:58 UTC, davidkornel commented
latest updates:
-startup probe removed
- updated CRDs
- monitoring enabled by default
- hostnetwork option added, default false
- auth service is added next to the operator it is installed by default, but can be turned off

2023-04-19 15:10 UTC, levaitamas commented
Resolves #11

2023-04-29 16:46 UTC, levaitamas commented
I rebased to `main` in order to get access to the new test actions from #13

2023-04-29 18:15 UTC, levaitamas requested changes
Thanks, this is truly great work! Made some comments, please check them.

2023-04-29 18:15 UTC, levaitamas commented on README.md
> +About the resource limits, in order to not stress the Kubernetes scheduler it is advised to keep the limits down and scale out (increase) the number of running pods if needed. Actually, it is the way
neat! love the xref to the fresh scaling doc :100:

2023-04-29 18:15 UTC, levaitamas commented on README.md
> +same CPU. This allows UDP listeners to scale to multiple CPUs.
I would mention at the end of the para that this can improve the performance

2023-04-29 18:15 UTC, levaitamas commented on README.md
> +- currently the max lifetime for `stunner` to remain alive after deleted in 1 hour: this means that `stunner` will remain active only for 1 hour after it has been deleted/scaled-down. You can always
after deleted in 1 -> after being deleted is 1

2023-04-29 18:15 UTC, levaitamas commented on README.md
> +Note that the default TURN refresh lifetime is 10 minutes so STUNner may remain alive well after the last client goes away. This occurs when an UDP allocation is left open by a client (spontaneous UD
and get deleted -> and gets deleted

2023-04-29 18:15 UTC, levaitamas commented on README.md
> +#### Disabling monitoring
Disabling -> Disable

2023-04-29 18:15 UTC, levaitamas commented on README.md
> +The default is to deploy STUNner with the monitoring port exposed in the STUNner pods to enable metric collection on K8s networking level.
The default is to deploy STUNner with ... -> By default STUNer is deployed with the monitoring port exposed in STUNner pods.

2023-04-29 18:15 UTC, levaitamas commented on README.md
> +In order to disable monitoring install the STUNner chart with the following command.
If you wish to avoid the port exposition, you can install STUNner with monitoring disabled:

2023-04-29 18:15 UTC, levaitamas commented on README.md
>  ## Deploying
just _Deploy_ or _Deploy STUNner with Helm_?

2023-05-02 11:09 UTC, levaitamas approved these changes

2023-05-02 11:31 UTC, merged